name: Build Spring Boot Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Change to your project's Java version
        distribution: 'temurin' # Or adopt if using AdoptOpenJDK

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the project
    - name: Build with Maven
      run: mvn clean package

    # Step 5: Archive the JAR artifact
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: spring-boot-app
        path: ./*.jar
    
     # Step 6: Log in to Docker Hub (set secrets in GitHub repository)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     # Step 7: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t myapp:v1.0 .
    # Step 8: Optionally, push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push myapp:v1.0
      if: github.ref == 'refs/heads/main' 