name: Build Spring Boot Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Change to your project's Java version
        distribution: 'temurin' # Or adopt if using AdoptOpenJDK

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the project
    - name: Build with Maven
      run: mvn clean package

    # Step 5: Archive the JAR artifact
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: spring-boot-app
        path: target/*.jar